// frontend/src/Components/Left_navbar_components/AccordionContent.svelte
<div class="accordion__text">
  <label>
    Vis: <br />
    <label for="vis">
      <input
        type="radio"
        class="radioButton"
        id="naavaarende"
        name="vis"
        defaultChecked="{true}"
      /> Nåværende medlemmer
    </label>
    <br />
    <label for="vis">
      <input type="radio" class="radioButton" id="naavaarende" name="vis" /> All
      time
    </label>
  </label>
  <br />
  <br />
  <label>
    Sorter etter: <br />
    <input
      type="radio"
      class="radioButton"
      id="flest"
      name="sort"
      defaultChecked="{true}"
    />
    <label for="vis">Flest straffer (verdi)</label>
    <br />
    <input type="radio" class="radioButton" id="minst" name="sort" />
    <label for="vis">Færrest straffer (verdi)</label>
  </label>
</div>

// frontend/Components/Left_navbar_components/AccordionContent.tsx
import React from "react";

const AccordionContent = () => {
  return (
    <div className="accordion__text">
      <label>
        Vis:
        <br />
        <label htmlFor="vis">
          <input
            type="radio"
            className="radioButton"
            id="naavaarende"
            name="vis"
            defaultChecked={true}
          />
          Nåværende medlemmer
        </label>
        <br />
        <label htmlFor="vis">
          <input
            type="radio"
            className="radioButton"
            id="naavaarende"
            name="vis"
          />
          All time
        </label>
      </label>
      <br />
      <br />
      <label>
        Sorter etter:
        <br />
        <input
          type="radio"
          className="radioButton"
          id="flest"
          name="sort"
          defaultChecked={true}
        />
        <label htmlFor="vis">Flest straffer (verdi)</label>
        <br />
        <input type="radio" className="radioButton" id="minst" name="sort" />
        <label htmlFor="vis">Færrest straffer (verdi)</label>
      </label>
    </div>
  );
};

export default AccordionContent;
