// frontend/src/Components/Left_navbar_components/SortNav.svelte
<script lang="ts">
  import SortAccordions from "./SortAccordions.svelte";
  import ChoosePunishments from "./ChoosePunishments.svelte";
</script>

<div class="sortNav">
  <div class="committeeName">
    <h2 class="groupTitle">Noe</h2>
    <hr>
  </div>

  <SortAccordions />
  <ChoosePunishments />
</div>

// frontend/Components/Left_navbar_components/SortNav.tsx
import React from "react";
import SortAccordions from "./SortAccordions";
import ChoosePunishments from "./ChoosePunishments";

import { getCurrentGroup } from "../Top_group_picker_components/GroupLogos";

const SortNav = () => {
  return (
    <div className="sortNav">
      <div className="committeeName">
        <h2 className="groupTitle">Noe</h2>
        <hr></hr>
      </div>

      <SortAccordions />
      <ChoosePunishments />
    </div>
  );
};

export default SortNav;
